// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5x8q6QN_htXiDiTlERKXovXNsXNFU4e8',
    appId: '1:99745095312:web:d13c47da759854ce644215',
    messagingSenderId: '99745095312',
    projectId: 'eventsaffairs-90430',
    authDomain: 'eventsaffairs-90430.firebaseapp.com',
    databaseURL: 'https://eventsaffairs-90430-default-rtdb.firebaseio.com',
    storageBucket: 'eventsaffairs-90430.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx1wdjo-PXe0zqZRmSiVANuRNPI_SNv5Y',
    appId: '1:99745095312:android:bbc343d62d2921c3644215',
    messagingSenderId: '99745095312',
    projectId: 'eventsaffairs-90430',
    databaseURL: 'https://eventsaffairs-90430-default-rtdb.firebaseio.com',
    storageBucket: 'eventsaffairs-90430.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA-e4YTS_diz-zqwfVqZV65aVK9cU6_d4',
    appId: '1:99745095312:ios:199d128eeead869f644215',
    messagingSenderId: '99745095312',
    projectId: 'eventsaffairs-90430',
    databaseURL: 'https://eventsaffairs-90430-default-rtdb.firebaseio.com',
    storageBucket: 'eventsaffairs-90430.firebasestorage.app',
    iosBundleId: 'com.example.eventsAffairs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA-e4YTS_diz-zqwfVqZV65aVK9cU6_d4',
    appId: '1:99745095312:ios:199d128eeead869f644215',
    messagingSenderId: '99745095312',
    projectId: 'eventsaffairs-90430',
    databaseURL: 'https://eventsaffairs-90430-default-rtdb.firebaseio.com',
    storageBucket: 'eventsaffairs-90430.firebasestorage.app',
    iosBundleId: 'com.example.eventsAffairs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5x8q6QN_htXiDiTlERKXovXNsXNFU4e8',
    appId: '1:99745095312:web:f7bedd8e6a1ad3ee644215',
    messagingSenderId: '99745095312',
    projectId: 'eventsaffairs-90430',
    authDomain: 'eventsaffairs-90430.firebaseapp.com',
    databaseURL: 'https://eventsaffairs-90430-default-rtdb.firebaseio.com',
    storageBucket: 'eventsaffairs-90430.firebasestorage.app',
  );

}